name: thetreeapptest
description: Test for thetreeapp.org

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.13.0"
  flutter: "2.2.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: 4.0.0
  get_it: 6.0.0
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: WorkSans
      fonts:
        - asset: lib/app/fonts/WorkSans-Regular.ttf